// LLMJudgeRunner.swift
// Thump Tests
//
// Tier B/C judge evaluation infrastructure.
//
// Architecture — two-phase separation:
//
//   Phase 1 (macOS host, outside XCTest):
//     run_judges.sh uses `claude --print` (Claude Code CLI) to run each persona
//     judge against captures and writes results as JSON to:
//       Tests/SuperReviewer/CaptureOutput/TierB/JudgeResults/*.json
//       Tests/SuperReviewer/CaptureOutput/TierC/JudgeResults/*.json
//
//   Phase 2 (XCTest, runs in iOS Simulator):
//     SuperReviewerTierBTests / SuperReviewerTierCTests load those pre-generated
//     JSON result files and run quality-gate assertions.
//
// This split means:
//   • No API key required in XCTest bundle
//   • Works in iOS Simulator context (only reads local files)
//   • Claude calls are handled by Claude Code's built-in auth (no ANTHROPIC_API_KEY)
//
// To run Tier B or C:
//   ./Tests/SuperReviewer/run_judges.sh [tierB|tierC]

import Foundation
@testable import Thump

// MARK: - LLM Judge Runner

struct LLMJudgeRunner {

    // MARK: - Load Pre-Generated Results (Phase 2 — XCTest)

    /// Loads judge results that were pre-generated by `run_judges.sh` on the macOS host.
    /// Returns an empty array if the directory doesn't exist (Tier B/C will skip).
    static func loadPreGeneratedResults(tier: LLMJudgeRegistry.JudgeTier) -> [MultiJudgeResult] {
        let dirName = tierDirName(tier)
        let sourceDir = URL(fileURLWithPath: #file).deletingLastPathComponent()
        let resultsDir = sourceDir
            .appendingPathComponent("CaptureOutput")
            .appendingPathComponent(dirName)
            .appendingPathComponent("JudgeResults")

        guard FileManager.default.fileExists(atPath: resultsDir.path) else {
            return []
        }

        let decoder = JSONDecoder()
        var results: [MultiJudgeResult] = []

        do {
            let files = try FileManager.default.contentsOfDirectory(
                at: resultsDir,
                includingPropertiesForKeys: nil
            ).filter { $0.pathExtension == "json" }

            for fileURL in files {
                if let data = try? Data(contentsOf: fileURL),
                   let result = try? decoder.decode(MultiJudgeResult.self, from: data) {
                    results.append(result)
                }
            }
        } catch {
            print("[SuperReviewer] Warning: could not load pre-generated results from \(resultsDir.path): \(error)")
        }

        return results
    }

    // MARK: - Evaluation (Phase 2 — triggered from run_judges.sh, not XCTest)

    /// Called from run_judges.sh via a small Swift CLI wrapper (not from XCTest).
    /// Evaluates a capture with all judges and returns the MultiJudgeResult.
    /// This function is only reachable on macOS via the CLI wrapper.
    static func evaluateBatch(
        captures: [SuperReviewerCapture],
        tier: LLMJudgeRegistry.JudgeTier,
        concurrency: Int = 3,
        delayBetweenBatchesMs: UInt64 = 500
    ) async -> [MultiJudgeResult] {
        var allResults: [MultiJudgeResult] = []

        let batches = stride(from: 0, to: captures.count, by: concurrency).map {
            Array(captures[$0..<min($0 + concurrency, captures.count)])
        }

        for (batchIdx, batch) in batches.enumerated() {
            let batchResults = await withTaskGroup(of: MultiJudgeResult.self) { group in
                for capture in batch {
                    group.addTask {
                        await evaluateWithAllJudges(capture: capture, tier: tier)
                    }
                }
                var results: [MultiJudgeResult] = []
                for await result in group { results.append(result) }
                return results
            }

            allResults += batchResults

            if batchIdx < batches.count - 1 {
                try? await Task.sleep(nanoseconds: delayBetweenBatchesMs * 1_000_000)
            }

            let processed = min((batchIdx + 1) * concurrency, captures.count)
            print("[SuperReviewer] Evaluated \(processed)/\(captures.count) captures")
        }

        return allResults
    }

    // MARK: - Save Results to Disk

    static func saveResults(_ results: [MultiJudgeResult], tier: LLMJudgeRegistry.JudgeTier) {
        let dirName = tierDirName(tier)
        let sourceDir = URL(fileURLWithPath: #file).deletingLastPathComponent()
        let resultsDir = sourceDir
            .appendingPathComponent("CaptureOutput")
            .appendingPathComponent(dirName)
            .appendingPathComponent("JudgeResults")

        try? FileManager.default.createDirectory(at: resultsDir, withIntermediateDirectories: true)

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]

        for result in results {
            let safeID = result.captureID
                .replacingOccurrences(of: "/", with: "_")
                .replacingOccurrences(of: " ", with: "-")
            let fileURL = resultsDir.appendingPathComponent("\(safeID).json")
            if let data = try? encoder.encode(result) {
                try? data.write(to: fileURL)
            }
        }

        print("[SuperReviewer] Saved \(results.count) judge results to \(resultsDir.path)")
    }

    // MARK: - Internal Evaluation (macOS only, via run_judges.sh)

    private static func evaluateWithAllJudges(
        capture: SuperReviewerCapture,
        tier: LLMJudgeRegistry.JudgeTier
    ) async -> MultiJudgeResult {
        let judges = LLMJudgeRegistry.availableJudges(for: tier)
        var results: [JudgeResult] = []
        var errors: [JudgeError] = []

        await withTaskGroup(of: Result<JudgeResult, Error>.self) { group in
            for judge in judges {
                group.addTask {
                    do {
                        let result = try await evaluate(capture: capture, judge: judge)
                        return .success(result)
                    } catch {
                        return .failure(error)
                    }
                }
            }
            for await result in group {
                switch result {
                case .success(let r): results.append(r)
                case .failure(let e): errors.append(.evaluationFailed(e.localizedDescription))
                }
            }
        }

        return MultiJudgeResult(
            captureID: "\(capture.personaName)_\(capture.journeyID)_d\(capture.dayIndex)_\(capture.timeStampLabel)",
            judgeResults: results,
            errors: errors
        )
    }

    private static func evaluate(
        capture: SuperReviewerCapture,
        judge: ClaudePersonaJudge,
        timeout: TimeInterval = 120
    ) async throws -> JudgeResult {
        let request = JudgeEvaluationRequest.build(judge: judge, capture: capture)
        let startTime = CFAbsoluteTimeGetCurrent()

        let rawResponse = try await callClaudeCLI(
            systemPrompt: judge.systemPrompt,
            userMessage: request.userMessage,
            modelAlias: judge.modelAlias,
            timeout: timeout
        )

        let elapsed = (CFAbsoluteTimeGetCurrent() - startTime) * 1000
        let evaluation = try parseClaudeCLIResponse(rawResponse)

        let captureID = "\(capture.personaName)_\(capture.journeyID)_d\(capture.dayIndex)_\(capture.timeStampLabel)"

        return JudgeResult(
            judgeID: judge.id,
            judgeName: judge.personaName,
            personaTitle: judge.personaTitle,
            captureID: captureID,
            response: evaluation,
            latencyMs: elapsed,
            timestamp: ISO8601DateFormatter().string(from: Date())
        )
    }

    // MARK: - Claude Code CLI Caller (macOS only)

    private static func callClaudeCLI(
        systemPrompt: String,
        userMessage: String,
        modelAlias: String,
        timeout: TimeInterval
    ) async throws -> String {
        // Process is macOS-only. This function is only called from run_judges.sh
        // on the macOS host, never from the iOS test bundle.
        #if os(iOS)
        throw JudgeError.evaluationFailed("callClaudeCLI: not available in iOS test bundle. Use run_judges.sh on macOS.")
        #else
        let claudePath = try LLMJudgeRegistry.claudeCLIPath()

        return try await withCheckedThrowingContinuation { continuation in
            let process = Process()
            process.executableURL = URL(fileURLWithPath: claudePath)
            process.arguments = [
                "--print",
                "--system-prompt", systemPrompt,
                "--model", modelAlias,
                "--no-session-persistence",
            ]

            let stdin  = Pipe()
            let stdout = Pipe()
            let stderr = Pipe()
            process.standardInput  = stdin
            process.standardOutput = stdout
            process.standardError  = stderr

            process.terminationHandler = { p in
                let outData  = stdout.fileHandleForReading.readDataToEndOfFile()
                let output   = String(data: outData, encoding: .utf8) ?? ""

                if p.terminationStatus == 0 {
                    continuation.resume(returning: output)
                } else {
                    let errData = stderr.fileHandleForReading.readDataToEndOfFile()
                    let errStr  = String(data: errData, encoding: .utf8)?.prefix(400) ?? "unknown"
                    continuation.resume(throwing: JudgeError.evaluationFailed(
                        "claude CLI exit \(p.terminationStatus): \(errStr)"
                    ))
                }
            }

            // Kill on timeout
            let pid = process
            Task {
                try? await Task.sleep(nanoseconds: UInt64(timeout * 1_000_000_000))
                if pid.isRunning { pid.terminate() }
            }

            do {
                try process.run()
            } catch {
                continuation.resume(throwing: JudgeError.evaluationFailed(
                    "Failed to launch claude CLI: \(error.localizedDescription)"
                ))
                return
            }

            if let data = userMessage.data(using: .utf8) {
                stdin.fileHandleForWriting.write(data)
            }
            stdin.fileHandleForWriting.closeFile()
        }
        #endif
    }

    // MARK: - Response Parsing

    private static func parseClaudeCLIResponse(_ rawText: String) throws -> JudgeEvaluationResponse {
        let jsonString = extractJSON(from: rawText)
            ?? rawText.trimmingCharacters(in: .whitespacesAndNewlines)

        guard let data = jsonString.data(using: .utf8) else {
            throw JudgeError.parseError("Could not convert CLI output to UTF-8 data")
        }

        do {
            return try JSONDecoder().decode(JudgeEvaluationResponse.self, from: data)
        } catch {
            throw JudgeError.parseError(
                "Failed to decode judge JSON: \(error)\nRaw (first 500): \(rawText.prefix(500))"
            )
        }
    }

    private static func extractJSON(from text: String) -> String? {
        if let start = text.range(of: "```json"),
           let end   = text.range(of: "```", range: start.upperBound..<text.endIndex) {
            return String(text[start.upperBound..<end.lowerBound])
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }
        if let start = text.range(of: "```"),
           let end   = text.range(of: "```", range: start.upperBound..<text.endIndex) {
            return String(text[start.upperBound..<end.lowerBound])
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }
        if let start = text.firstIndex(of: "{"),
           let end   = text.lastIndex(of: "}") {
            return String(text[start...end])
        }
        return nil
    }

    // MARK: - Helpers

    private static func tierDirName(_ tier: LLMJudgeRegistry.JudgeTier) -> String {
        switch tier {
        case .primary:   return "TierA_Primary"
        case .secondary: return "TierB"
        case .tertiary:  return "TierC"
        }
    }
}

// MARK: - Multi-Judge Result

struct MultiJudgeResult: Codable {
    let captureID: String
    let judgeResults: [JudgeResult]
    let errors: [JudgeError]

    /// Raw average overall_score across judges (scale varies by judge format, 0–100 or 0–150).
    var consensusScore: Double {
        guard !judgeResults.isEmpty else { return 0 }
        return judgeResults.map(\.response.overallScore).reduce(0, +) / Double(judgeResults.count)
    }

    /// Normalized score as a percentage (0–100) regardless of each judge's max_possible scale.
    var percentageScore: Double {
        guard !judgeResults.isEmpty else { return 0 }
        let pcts = judgeResults.map { r -> Double in
            let max = r.response.maxPossible > 0 ? r.response.maxPossible : 100
            return (r.response.overallScore / max) * 100
        }
        return pcts.reduce(0, +) / Double(pcts.count)
    }

    var scoreVariance: Double {
        guard judgeResults.count > 1 else { return 0 }
        let mean = consensusScore
        let sumSqDiff = judgeResults.map { pow($0.response.overallScore - mean, 2) }.reduce(0, +)
        return sumSqDiff / Double(judgeResults.count - 1)
    }

    var disagreedCriteria: [String] {
        guard judgeResults.count > 1 else { return [] }
        var disagreements: [String] = []
        let allCriteria = Set(judgeResults.flatMap { $0.response.scores.keys })
        for criterion in allCriteria {
            let scores = judgeResults.compactMap { $0.response.scores[criterion]?.score }
            if let minScore = scores.min(), let maxScore = scores.max(), maxScore - minScore > 2 {
                disagreements.append(criterion)
            }
        }
        return disagreements.sorted()
    }
}

// MARK: - Errors

enum JudgeError: Error, Codable, LocalizedError {
    case claudeCLINotFound
    case apiError(statusCode: Int, body: String)
    case invalidResponse
    case parseError(String)
    case evaluationFailed(String)
    case timeout

    var errorDescription: String? {
        switch self {
        case .claudeCLINotFound:            return "claude CLI not found — install Claude Code"
        case .apiError(let code, let body): return "API error \(code): \(body.prefix(200))"
        case .invalidResponse:              return "Invalid response"
        case .parseError(let msg):          return "Parse error: \(msg)"
        case .evaluationFailed(let msg):    return "Evaluation failed: \(msg)"
        case .timeout:                      return "Request timed out"
        }
    }
}

// MARK: - Report Generation

struct SuperReviewerReport {
    let config: String
    let totalCaptures: Int
    let totalJudgeRuns: Int
    let programmaticResults: BatchVerificationResult
    let llmResults: [MultiJudgeResult]
    let durationMs: Double

    func generateReport() -> String {
        var lines: [String] = []
        lines.append("╔══════════════════════════════════════════════════════╗")
        lines.append("║          SUPER REVIEWER EVALUATION REPORT           ║")
        lines.append("╚══════════════════════════════════════════════════════╝")
        lines.append("")
        lines.append("Configuration: \(config)")
        lines.append("Total captures: \(totalCaptures)")
        lines.append("Total LLM judge runs: \(totalJudgeRuns)")
        lines.append("Duration: \(String(format: "%.1f", durationMs / 1000))s")
        lines.append("")
        lines.append("── Programmatic Verification ──")
        lines.append(programmaticResults.summary())
        lines.append("")

        if !llmResults.isEmpty {
            lines.append("── Persona Judge Results ──")
            let avgPct = llmResults.map(\.percentageScore).reduce(0, +) / Double(max(llmResults.count, 1))
            lines.append("Average score: \(String(format: "%.1f", avgPct))% (normalized)")
            let minPct = llmResults.map(\.percentageScore).min() ?? 0
            let maxPct = llmResults.map(\.percentageScore).max() ?? 0
            lines.append("Score range: \(String(format: "%.1f", minPct))% – \(String(format: "%.1f", maxPct))%")
            lines.append("")

            let judgeIDs = Set(llmResults.flatMap { $0.judgeResults.map(\.judgeID) })
            for judgeID in judgeIDs.sorted() {
                let scores = llmResults.flatMap { $0.judgeResults.filter { $0.judgeID == judgeID } }
                let avg = scores.map(\.response.overallScore).reduce(0, +) / Double(max(scores.count, 1))
                let name = scores.first.map { "\($0.judgeName) (\($0.personaTitle))" } ?? judgeID
                lines.append("  \(name): avg \(String(format: "%.1f", avg)) (\(scores.count) evaluations)")
            }

            let allDisagreements = llmResults.flatMap(\.disagreedCriteria)
            let disagreeCount = Dictionary(grouping: allDisagreements, by: { $0 }).mapValues(\.count)
            if !disagreeCount.isEmpty {
                lines.append("")
                lines.append("Most disagreed criteria:")
                for (criterion, count) in disagreeCount.sorted(by: { $0.value > $1.value }).prefix(5) {
                    lines.append("  \(criterion): \(count) disagreements")
                }
            }

            let allCritical = llmResults.flatMap { r in r.judgeResults.flatMap { $0.response.criticalIssues } }
            if !allCritical.isEmpty {
                lines.append("")
                lines.append("Critical issues flagged by persona judges:")
                for issue in Array(Set(allCritical)).sorted().prefix(10) {
                    lines.append("  ⚠️  \(issue)")
                }
            }

            lines.append("")
            lines.append("── Persona Reactions (sample) ──")
            for judgeResult in llmResults.first?.judgeResults ?? [] {
                if let reaction = judgeResult.response.personaReaction {
                    lines.append("")
                    lines.append("[\(judgeResult.judgeName)]")
                    lines.append(reaction)
                }
            }
        }

        lines.append("")
        lines.append("══════════════════════════════════════════════════════")
        return lines.joined(separator: "\n")
    }
}
